### ISSUE TITLE
Update Readme ...

### ISSUE THREAD

**Issue by mgmart** [WorkoutExporter/WorkoutExporter#14]
... at least with new screenshots

**Comment by patricks** [comment]
An please also rename the file to `README.md`. Now we also could add the travis-ci badge.

**Comment by mgmart** [comment]
The Readme is written in org-mode at the moment. A simple rename would result in garbage 🤔 

<img width="298" alt="bildschirmfoto 2019-01-27 um 11 59 27" src="https://user-images.githubusercontent.com/3919652/51800116-17381400-222b-11e9-8f0e-a2e4255cda55.png">

<img width="593" alt="bildschirmfoto 2019-01-27 um 11 58 45" src="https://user-images.githubusercontent.com/3919652/51800126-24550300-222b-11e9-8b03-5f8a433f155d.png">

Would you like to give org-mode a try?

👍 for the badge

**Comment by patricks** [comment]
A didn't know that, sure let's use org-mode. 😄
