### ISSUE TITLE
Replace current app icon and name

### ISSUE THREAD

**Issue by patricks** [WorkoutExporter/WorkoutExporter#21]
We should think about a new app name, this one is in my opinion a little bit too long.

![img_2930](https://user-images.githubusercontent.com/132167/51802922-3183e900-224f-11e9-8d2a-e8debba896f3.jpg)

We should also think about a new app icon.

**Comment by mgmart** [comment]
Agree, although I spent some time to come up with this icon 😆

**Comment by mgmart** [comment]
The new icon looks really nice. Should we come up with an alternate icon to have in hand if the current one is rejected by Apple during approval?
This should only be an issue if we decide to publish the app.

**Comment by patricks** [comment]
I would suggest, that we create a create an alternative icon, if we get rejected 😉.
