### ISSUE TITLE
Exporting of multiple workouts at once

### ISSUE THREAD

**Issue by mgmart** [WorkoutExporter/WorkoutExporter#6]

**Comment by patricks** [comment]
I think this issue is already implemented?

**Comment by mgmart** [comment]
It might work with two or three small files. At some point the resulting GPX files become corrupt. Some of the files are not written completely.

**Comment by mgmart** [comment]
Maybe I remembered that wrong: I just found a stray ```"``` in GPX generation.

https://github.com/WorkoutExporter/WorkoutExporter/blob/b5fb40b08ecbcc3bb3ea875cce19de934488ebbc/GpxExport/Models/Workout.swift#L149

I wait with a fix until you've got the refactoring ready, ok?

**Comment by patricks** [comment]
The main refactoring is finished, there is only one PR open 😉.

**Comment by mgmart** [comment]
Yeah. I'm just trying to figure out how to remove the ```Podfile.lock```and ```GpxExport.xcworkspace/xcshareddata``` from the PR 🤓
